Fix/company create offer
NIAEFEUP/nijobs-be pull request #167
Opened 2021-08-07 21:55 UTC by Naapperas

Closes #144

2021-08-07 22:00 UTC, Naapperas commented
Regarding the tests, I didn't add any specific tests for the added behavior, but rather updated one that circumvented the problem by setting manually the offer owner. With that change, it confirms the new middleware works. If I should add more tests or modify existing ones, please let me know.

2021-08-07 23:05 UTC, imnotteixeira requested changes
As stated in #144, https://github.com/NIAEFEUP/nijobs-be/blob/1b277c87e024329ea5173b7b0e9fb9fd67fcb12a/src/services/offer.js#L231 might also need a change, by having it like so:

```js
if (offer?.isHidden && !(user?.isAdmin || offer.owner.toString() === req.targetOwner)) return null;
```

2021-08-07 23:05 UTC, imnotteixeira commented on src/api/middleware/auth.js
> +    req.ownerCompany = req.user?.company || req.body.owner;
req.user?.company shouldn't be instead req.user?.company?._id.toString() ?

2021-08-08 00:41 UTC, Naapperas commented
> As stated in #144,
> 
> https://github.com/NIAEFEUP/nijobs-be/blob/1b277c87e024329ea5173b7b0e9fb9fd67fcb12a/src/services/offer.js#L231
> might also need a change, by having it like so:
> 
> ```js
> if (offer?.isHidden && !(user?.isAdmin || offer.owner.toString() === req.targetOwner)) return null;
> ```

That line as already been changed by #154 to account for requests made by a god (that's what was pointed in #144).

https://github.com/NIAEFEUP/nijobs-be/blob/f710a3047f395b9790f9fe6424404cdc4122c148/src/services/offer.js#L237

Still, I'll apply this change to make it more coherent with the rest of the code.

2021-08-08 00:48 UTC, Naapperas commented on src/api/middleware/auth.js
> +    req.ownerCompany = req.user?.company || req.body.owner;
I thought so, but the issue stated that the replacement should be `req.user?.company || req.body.owner`, so I went with that.

2021-08-08 00:51 UTC, Naapperas commented on src/api/middleware/auth.js
> +    req.ownerCompany = req.user?.company || req.body.owner;
After looking through the code, i found this:

https://github.com/NIAEFEUP/nijobs-be/blob/f710a3047f395b9790f9fe6424404cdc4122c148/src/models/Account.js#L24-L25

So this should be kept as is.

2021-08-08 01:10 UTC, imnotteixeira commented on src/api/middleware/auth.js
> +    req.ownerCompany = req.user?.company || req.body.owner;
The thing is: the owner in the request will always be a string (which is an ObjectId, as long as it has the right format). Also, as you can see in https://github.com/NIAEFEUP/nijobs-be/blob/f710a3047f395b9790f9fe6424404cdc4122c148/src/services/offer.js#L237, the code always accesses the company id by accessing the user.company._id.toString(), therefore if we are to replace those occurrences with the targetOwner variable, it should keep the same logic I think, unless it doesn't work for some reason I am not understanding at the moment.

> the replacement should be req.user?.company || req.body.owner
this was a quick suggestion from me, take it with a grain of salt

2021-08-08 01:11 UTC, imnotteixeira commented
> 
> 
> > As stated in #144,
> > https://github.com/NIAEFEUP/nijobs-be/blob/1b277c87e024329ea5173b7b0e9fb9fd67fcb12a/src/services/offer.js#L231
> > 
> > might also need a change, by having it like so:
> > ```js
> > if (offer?.isHidden && !(user?.isAdmin || offer.owner.toString() === req.targetOwner)) return null;
> > ```
> 
> That line as already been changed by #154 to account for requests made by a god (that's what was stated in #144).
> 
> https://github.com/NIAEFEUP/nijobs-be/blob/f710a3047f395b9790f9fe6424404cdc4122c148/src/services/offer.js#L237
> 
> Still, I'll apply this change to make it more coherent with the rest of the code.

Yes, the relevant part still requires updating, concerning the changes in this PR

2021-08-08 15:19 UTC, imnotteixeira approved these changes

2021-08-08 15:47 UTC, merged