Fixed all tests
NIAEFEUP/nijobs-be pull request #278
Opened 2022-12-06 17:15 UTC by marco-vb

2022-12-07 12:47 UTC, Naapperas requested changes
This looks good. The only thing needed is to pick better commit names

2022-12-07 12:47 UTC, Naapperas commented on test/end-to-end/company.js
> +        jobMaxDuration: 6,
This applies to the rest of the lines that are like these: when the tests are refactored (see #169 ) these should be put in the offer creation utility.

2022-12-15 16:00 UTC, Naapperas approved these changes

2022-12-18 02:13 UTC, BrunoRosendo commented
@marco-vb Please update the API documentation with this change. It is stored under `docs/` and the syntax resembles markdown, you can read the docs (in the README) to know how to use it.

2022-12-18 02:13 UTC, BrunoRosendo requested changes
@marco-vb Please update the API documentation with this change. It is stored under docs/ and the syntax resembles markdown, you can read the docs (in the README) to know how to use it.

2022-12-23 18:40 UTC, Naapperas requested changes

2022-12-23 18:40 UTC, Naapperas commented on documentation/docs/offers/create.md
Should be marked as required, as you have done for `jobMaxDuration`

2023-01-17 17:37 UTC, Naapperas approved these changes
LGTM

2023-01-17 18:28 UTC, BrunoRosendo approved these changes
Looks good!

2023-01-18 01:05 UTC, merged