214 add extra company information
NIAEFEUP/nijobs-be pull request #303
Opened 2023-02-07 16:19 UTC by CiscoPr

8 tests are failing but the main code is done. Needs some reviews to discover where the errors are.

2023-02-08 10:02 UTC, Naapperas requested changes

2023-02-08 10:02 UTC, Naapperas commented on src/api/middleware/files.js
> +        const filename = `${req.user.company}.${extension}`;
This line will make it so every file this company uploads has the same name. Maybe add a nonce or a sequence number to make the name unique.

2023-02-08 23:16 UTC, diogofonte reviewed
The code and the tests implemented seem good to me, but the support for adding several locations is available? I didn't notice it in the files changes. I'm asking this because of this comment: https://github.com/NIAEFEUP/nijobs-be/issues/214#issuecomment-1307352719

2023-02-09 17:13 UTC, CiscoPr commented
> The code and the tests implemented seem good to me, but the support for adding several locations is available? I didn't notice it in the files changes. I'm asking this because of this comment: [#214 (comment)](https://github.com/NIAEFEUP/nijobs-be/issues/214#issuecomment-1307352719)

yes i forgot to add that, thanks for reminding me.
@Naapperas, these several locations is also an optional company field or does it must have a minimal length?

2023-02-12 00:46 UTC, DoStini commented
Just a note: commits should try to be small. On a more important note, commits should explain what it does or what it solves, and not the state of the issue. 

We also standardized using rebase instead of merge (from develop), if need help in this reach us

2023-02-14 14:42 UTC, pedronunes19 commented on test/end-to-end/company.js
> +                test("should return an error because the social media is too long", async () => {
Shouldn't the text be about the images?

2023-06-18 23:01 UTC, Naapperas requested changes

2023-06-18 23:01 UTC, Naapperas commented on src/api/routes/company.js
> +                const images = req?.files?.map((file) => file?.url || `${config.webserver_host}/static/${file.filename}`) ?? [];
Perhaps this should be a function: should we need this logic elsewhere we only need to change it in one place.

2024-03-06 12:29 UTC, closed without merging

2024-03-14 03:44 UTC, Naapperas commented
@CiscoPr What happened?

2024-03-14 11:09 UTC, CiscoPr commented
@Naapperas i just created another  branch for this issue and I will open another PR with it. I wanted to start it over again to be less confusing since this one was really outdated